@Host:  = http://localhost:5042

POST {{Host:}}/api/contacts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john12@email.com",
  "phoneNumber": "+998991011010",
  "address": "England, London"
}
###

GET {{Host:}}/api/contacts
###

GET {{Host:}}/api/contacts/4
###

PATCH {{Host:}}/api/contacts/4
Content-Type: application/json

{
  "phoneNumber": "+998991231234"
}
###

PUT {{Host:}}/api/contacts/5
Content-Type: application/json

{
  "firstName": "Alisher",
  "lastName": "Maxamadjonov",
  "email": "alisher@gmail.com",
  "phoneNumber": "+998331234567",
  "address": "Tashkent, Uzbekistan"
}
###

DELETE {{Host:}}/api/contacts/2
###