@Host:  = http://localhost:5042

POST {{Host:}}/api/contacts
Content-Type: application/json

{
  "firstName": "Alisher",
  "lastName": "Maxamadjonov",
  "email": "maxamadjonov@gmail.com",
  "phoneNumber": "+998991011010",
  "address": "Tashkent, Uzbekistan"
}
###

GET {{Host:}}/api/contacts
###

GET {{Host:}}/api/contacts/2
###

PATCH {{Host:}}/api/contacts/1
Content-Type: application/json

{
  "id": 3,
  "phoneNumber": "+998991231234"
}
###

PUT {{Host:}}/api/contacts/1
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Doe",
  "email": "john@gmail.com",
  "phoneNumber": "+998331234567",
  "address": "England, London"
}
###

DELETE {{Host:}}/api/contacts/2
###